resource_group_location = "westus"
resource_group_name     = "terraformazurequickstarts"
subscription_id         = "your-subscription-id" 
tenant_id               = "your-tenant-id" 
client_id               = "your-client-id" 
client_secret           = "your-client-subscription" 